tweetafeeling:
   build: .
   ports:
      - "4242:4242"
   volumes:
      - .:/code
   links:
      - orion
      - rabbitmq
      - mongo

orion:
   image: fiware/orion
   ports:
      - "1026:1026"
   links:
      - mongo
   command: -dbhost mongo

mongo:
   image: mongo:2.6
   command: --smallfiles --nojournal

rabbitmq:
   image: rabbitmq:3-management
   ports:
      - "15672:15672"
